- dist/LeafletEnvironmentalLayers.js
- src/skyTruthLayer.js
> skytruth url corrected

- dist/LeafletEnvironmentalLayers.js
- example/mapSimple.html
- src/leafletEnvironmentalLayers.js
- src/mapKnitterLayer.js
> mapKnitterLayer 

- dist/LeafletEnvironmentalLayers.js
- example/index.html
- src/mapKnitterLayer.js
> mapknitter marker changed

- dist/LeafletEnvironmentalLayers.js
- src/mapKnitterLayer.js
> mapknitter marker pop up changed

- dist/LeafletEnvironmentalLayers.js
- src/mapKnitterLayer.js
> mapknitter size changed

- README.md
In this PR we can work on improving the Readme .
📓 📔 🗒 📝 ✏️
> ReadMe Minor Change

- package.json
- Mapknitter markers size reduced to half !
> Minor version bump

- dist/LeafletEnvironmentalLayers.js
- src/mapKnitterLayer.js
- src/skyTruthLayer.js
Layers URL changed :  
1.) Mapknitter 
2.) SkyTruth
Fixes https://github.com/publiclab/mapknitter/issues/276 !
> truncation of coordinates removed

- dist/LeafletEnvironmentalLayers.js
- package-lock.json
- src/fractracker.js
- src/odorReportLayer.js
- src/purpleAirMarkerLayer.js
- src/skyTruthLayer.js
> url link corrected in layers 

- README.md
@sagarpreet-chadha Please take a look :)
> Add table in readme.

- src/fractracker.js
Fixes #68 .
This should fix this 😃 🎈 .
> Url of marker changed to https .

- dist/LeafletEnvironmentalLayers.js
- example/index.html
- src/indigenousLandsTerritoriesLayer.js
- src/leafletEnvironmentalLayers.js
Fixes #55 
2 of 3 PRs
Implemented the Indigenous Lands **Territories** Layer
Works similar to #76 and #78 .
I have decided to get data only for the specific section rather than the whole map because the territories and treaties layers are quite more complex than the languages ones. I have set clearOutsideBounds to false for now.
Please tell me if you would like me to change anything.
Happy to be contributing,
Kevin Luo
> Added the Indigenous Lands **Territories** Layer. Indigenous Lands Territories Inventory

- dist/LeafletEnvironmentalLayers.js
- src/purpleAirMarkerLayer.js
Fixes #41 ! 
**Only fetching data from API if zoom level >= 7 .** 
* Now works smoothly !
> Overload with PurpleAir layer when viewing whole world - Solved  #41

- example/index.html
- package-lock.json
- package.json
> Version bump 1.1.1

- package.json
> patch version bump . 

- README.md
- example/index.html
> mobile fractracker layer added

- README.md
- example/index.html
> Wisconsin Non metallic layer added

- dist/LeafletEnvironmentalLayers.js
- src/fractracker.js
Fixes #73 .
When I first tried using the CSV links in issue, I encountered CORS errors.
So, after digging around, I managed to find this website that explained how to get data from a published spreadsheet - and its even in JSON. It turns out there is a Spreadsheet API that allows for this. 
Afterwards, I just rewrote some methods and refactored some code.
> Live loading from google spreadsheet for Fractracker

- example/index.html
Showing way to tell people about Layers button  #62  .
> Layer control button modified

- CODE_OF_CONDUCT.md
Fixes #114
Copied CODE_OF_CONDUCT.md from /publiclab/plots2.
> Add code of conduct (Issue #114)

- dist/LeafletEnvironmentalLayers.js
- src/aqicnLayer.js
- src/fractracker.js
- src/indigenousLandsLanguagesLayer.js
- src/indigenousLandsTerritoriesLayer.js
- src/indigenousLandsTreatiesLayer.js
- src/luftdatenLayer.js
- src/mapKnitterLayer.js
- src/odorReportLayer.js
- src/openaqLayer.js
- src/purpleAirMarkerLayer.js
- src/purpleLayer.js
- src/skyTruthLayer.js
The lines of code that appended jQuery to the head tag have been re-written to check if jQuery has been added before appending it to the head.
fixes #95
> prevent jQuery from being loaded multiple times

- example/index.html
Fixes #145 
- I have added the character encoding at the top of the index.html file.
- There is no longer an error on the console.
Previously console gave this error
> Declared character encoding for index.html

- example/index.html
@jywarren @sagarpreet-chadha @gauravano Added some documentation so that newcomers can understand the code easily. Also shifted the styles under one tag . Please review.
> Structured and added some documentation to the code.

- dist/LeafletEnvironmentalLayers.js
- example/index.html
- src/aqicnLayer.js
- src/fracTrackerMobileLayer.js
- src/legendCreation.js
- src/luftdatenLayer.js
- src/openSenseLayer.js
- src/openWeatherMapLayer.js
- src/openaqLayer.js
- src/purpleLayer.js
- src/util/legendControl.js
- src/windRoseLayer.js
Hey guys, 
Its my first time contributing to this repo and I am not sure of the testing procedures. It seems there aren't any unit tests configured yet, so I basically tested all of the layers my code changes in Chrome to make sure they still turn on and off. 
I also reverted a commit that seems to have broken the example in order to make this branch work. @sidntrivedi012, this was your commit, and it looks like @jywarren merged it. Im not sure of the procedures here, so I just reverted it on my branch, and will wait for your instructions. 
Thanks!
Fixes #150
> Fixes assorted JS errors

- README.md
- example/index.html
@jywarren @sagarpreet-chadha @gauravano Please review.
> Added SEO meta tags and made some changes in README.

- README.md
Fixes #176 
I add a npm badge to README
> Add npm package badge to README.md

- README.md
Adding bower badge @sagarpreet-chadha.
I add 2 different badges. The first badge quite nicer than the second one. But the first badge, I can't find leaflet-environmental-layers on [Bower](https://bower.io/search).
> WIP: Add bower badge

- README.md
Fixes #178 (FTO)
Added the JS Coding Style Badge to the README file.
Thanks!
> Added JS Coding Style Badge to README

- example/index.html
Fixes #189  (<=== Add issue number here)
Thanks!
> Changed onload baselayer from greyscale to standard

- example/index.html
> Code redundancy and meta tag issues solved

- example/index.html
> Changed css of LEL menu

- example/index.html
> Changed menu width of layer menu

- example/index.html
> categorization of some layers done

- README.md
> Grunt instructions added to Readme.md

- example/index.html
> Layer menu popup positioned to bottom right

- example/index.html
- example/styles.css
Fixes #213
- [✔️] PR is descriptively titled 📑 and links the original issue above [🔗]
- [✔️] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
- [✔️] code is in a uniquely-named feature branch and has no merge conflicts 📁
- [✔️] screenshots/GIFs are attached 📎 in case of UI updation
- [✔️] ask @publiclab/reviewers for help, in a comment below
> separate html and css

- README.md
Fixes #215 (<=== Add issue number here)
Fixes #177
Thanks!
> PR to Add Code of Conduct badge in readme | Add Licence badge in readme

- dist/LeafletEnvironmentalLayers.css
- dist/LeafletEnvironmentalLayers.js
- package.json
- src/mapKnitterLayer.js
Follow-up to #13 -- cc @ananyaarun @sagarpreet-chadha !
> style tweaks and only displaying maps with at least one image

- example/layers.js
> Updated layer.js to include PLpeople layer

- dist/LeafletEnvironmentalLayers.js
- package.json
- src/mapKnitterLayer.js
> fix #220 for mapknitter layer

- dist/LeafletEnvironmentalLayers.js
- package.json
- src/mapKnitterLayer.js
> path fixes

- CONTRIBUTING.md
- README.md
> Added testing instructions to docs

- spec/javascripts/fixtures/mapknitterLayer.html
- spec/javascripts/mapknitterLayer_spec.js
> [WIP] Jasmine tests for layers 

- dist/LeafletEnvironmentalLayers.js
- example/layers.js
- example/oneLinerCodeExample.html
- package.json
- src/AllLayers.js
- src/leafletEnvironmentalLayers.js
Fixes #175
```
L.LayerGroup.EnvironmentalLayers({
include: ['mapknitter', 'clouds'],
hash: true,
}).addTo(map);
```
> One liner code to add all layers . 

- README.md
> Adds syntax for adding all layers (using include/exclude/hash)

- CONTRIBUTING.md
This PR is with reference to a previous PR (#158 ). The previous implementation had missed out providing link to the codepen it mentions. This has been corrected in this PR.
> docs: modify CONTRIBUTING.md

- _SpecRunner.html
- dist/LeafletEnvironmentalLayers.js
- example/index.html
- example/layers.js
- src/layercode.js
- src/pfasLayer.js
- src/util/spiderfyMarkers.js
Fixes #258  (<=== Add issue number here)
Thanks!
> Use overlapping marker spiderfier plugin to spread out markers

- README.md
Fixes #238 (<=== Add issue number here)
Thanks!
> Added missing new layers to README.md table

- dist/LeafletEnvironmentalLayers.js
- example/oneLinerCodeExample.html
- package.json
- src/AllLayers.js
Hey @crisner , these changes were missing in your PR's.  See AllLayer.js file on how to do changes there.
> AllLayer feature added new Layers - eonetfireLayer

- dist/LeafletEnvironmentalLayers.js
- example/layers.js
- example/oneLinerCodeExample.html
- package.json
- src/AllLayers.js
- src/layercode.js
- src/pfasLayer.js
Reverted Spiderify feature, giving problems in plots2!
> reverted spiderify

- src/pfasLayer.js
Fixes [#271](https://github.com/publiclab/leaflet-environmental-layers/issues/271)
Thanks!
Screenshot attached(after running grunt build) :
> Remove iconANchor property and change values in popupAnchor property

- src/AllLayers.js
Fixes https://github.com/publiclab/plots2/issues/6889 (<=== Add issue number here)
Thanks!
> Fixes map permalinks overwrite issue on plots2

- example/layers.js
- example/styles.css
- src/util/displayInfo.js
Fixes #308  (<=== Add issue number here)
Thanks!
> Display directions on top of map

- README.md
Fixes #304  (<=== Add issue number here)
Thanks!
> Added hashed support ,Updated Readme

- README.md
Fixes #305  
I updated the README file with documentation for the newly implemented embed feature.
Thanks!
> Update README.md with documentation for embed feature

- src/layerData.json
- src/util/layersBrowser.js
Fixes #331  (<=== Add issue number here)
Thanks!
> Remove use of hardcoded extents for displaying layers

- dist/LeafletEnvironmentalLayers.js
- spec/javascripts/embedControl.spec.js
- src/util/embedControl.js
Fixes #338  (<=== Add issue number here)
Thanks!
> Fix embed code with duplicated text

- src/util/layersBrowser.js
> Add check that layers group is not undefined when creating layers-sub-list

- dist/LeafletEnvironmentalLayers.js
- package-lock.json
- src/util/layersBrowser.js
Fixes #133  (<=== Add issue number here)
Thanks!
> Display new items mark in layers menu

- dist/LeafletEnvironmentalLayers.js
- src/layerData.json
- src/util/layersBrowser.js
Fixes #337  (<=== Add issue number here)
Thanks!
> Add contribute button to open infra map

- example/styles.css
Fixes #344  (<=== Add issue number here)
Thanks!
> Add media queries for size 235x300

- dist/LeafletEnvironmentalLayers.js
- package-lock.json
- package.json
Bumping version to 2.2.0
and leaflet-blurred-location to 1.7.0
so that the recent changes will work on plots2
> version 2.2.0 and bump LBL to 1.7.0

- dist/LeafletEnvironmentalLayers.js
- package.json
> Added pre/post publish script and bumped version to 2.2.1

- README.md
- dist/LeafletEnvironmentalLayers.js
- example/embed.html
- example/index.html
- example/multipleMaps.html
- example/oneLinerCodeExample.html
- example/unearthing-pvd.html
- src/osmLandfillMineQuarryLayer.js
- src/pfasLayer.js
- src/toxicReleaseLayer.js
- src/util/googleSpreadsheetLayer.js
Fixes #372  (<=== Add issue number here)
Thanks!
> Fix duplication of jquery scripts

- cypress/integration/hashChange.spec.js
- cypress/integration/indexDemo.spec.js
Fixes #411 (<=== Add issue number here)
Thanks!
> Change wait time to 100ms

- cypress/fixtures/fractrackerMobile.json
- cypress/integration/fractrackerMobile.spec.js
Fixes #415  (<=== Add issue number here)
Thanks!
> Add tests for fractrackerMobile layer

- cypress/fixtures/eonetFiresLayer.json
- cypress/integration/eonetFiresLayer.spec.js
Fixes #405  (<=== Add issue number here)
Thanks!
> Add tests for Eonet Fires Layer

- cypress/fixtures/pfasLayer.json
- cypress/integration/pfasLayer.spec.js
Fixes #418  (<=== Add issue number here)
Thanks!
> Add tests for Pfas layer

- cypress/fixtures/aqicn.json
- cypress/integration/aqicn.spec.js
Fixes #435  (<=== Add issue number here)
Thanks!
> Add tests for aqicn layer

- cypress/integration/osmLandfill.spec.js
- cypress/integration/unearthing.spec.js
- dist/LeafletEnvironmentalLayers.js
- src/osmLandfillMineQuarryLayer.js
Fixes #437  (<=== Add issue number here)
Thanks!
> Add tests for osmlandfill layer and unearthing layer

- spec/javascripts/basicImplementation.spec.js
Fixes #451  (<=== Add issue number here)
Thanks!
> Fix test errors caused by 'new L.Control.GPlaceAutocomplete'

- dist/LeafletEnvironmentalLayers.js
- example/layers.js
- package.json
- src/AllLayers.js
> update AllLayers.js to new MapBox API (will need patch release)

- cypress/fixtures/skytruth.json
- cypress/integration/skytruth.spec.js
- dist/LeafletEnvironmentalLayers.js
- example/oneLinerCodeExample.html
- package-lock.json
- package.json
- src/info.json
- src/layercode.js
fixes #118
fixes #336 
Thanks!
> Update skytruth api params to v2, fix display

- cypress/integration/owm.spec.js
- dist/LeafletEnvironmentalLayers.js
- example/oneLinerCodeExample.html
- package.json
- src/AllLayers.js
- src/openWeatherMapLayer.js
> revised fix for owmloading.gif

- package-lock.json
- package.json
Fixes https://github.com/publiclab/plots2/pull/10033
CC @daemon1024
> Require LBLD v1.3.1

- dist/LeafletEnvironmentalLayers.js
- package-lock.json
- package.json
Last version didn't have the updated file in dist/* so the [purpleair fix](https://github.com/publiclab/leaflet-environmental-layers/pull/554/commits/4b2e00c52af08bba67d43b4bb50b0d35f1c75e99) didn't exist in the published version
and
We need to explicitly require LBLD v1.3.2 because plots2 is still using the older version even after the bump
> require LBLD v1.3.2 and bump LEL to v2.4.7

- dist/LeafletEnvironmentalLayers.js
- package-lock.json
- package.json
- src/PLpeopleLayer.js
Fixes https://github.com/publiclab/leaflet-blurred-location-display/pull/136#issuecomment-901314290 https://github.com/publiclab/plots2/pull/10050#issuecomment-901273164
> parse title in JSONParser for LBLD
