publiclab/leaflet-environmental-layers

README.md
example/mapSimple.html

OpenInfraLayer Added

---

dist/LeafletEnvironmentalLayers.js
example/index.html
src/indigenousLandsLanguagesLayer.js
src/leafletEnvironmentalLayers.js

Fixes #55 
@jywarren @sagarpreet-chadha 
1 of 3 PRs
Works similar to #77 and #78 .
I have implemented a layer for the Languages section of the Native Land API. Because we are not yet able to fetch the data from the API, I have used some sample data for now.
Here it is in action:
I still need to add one for the territories and treaties sections. **Would you like me to continue them on this PR or to make 2 new ones?** The code will likely be very similar.
I have asked Native Lands about their API and hopefully they respond soon.
Thank you,
Kevin Luo

Added Indigenous Lands **Languages** Layer. Indigenous Lands Languages Inventory

---

dist/LeafletEnvironmentalLayers.js
example/index.html
src/indigenousLandsTreatiesLayer.js
src/leafletEnvironmentalLayers.js

Fixes #55 
3 of 3 PRs
Implemented the Indigenous Lands **Treaties** Layer
Works similar to #76, #77 .
I have decided to get data only for the specific section rather than the whole map because the territories and treaties layers are quite more complex than the languages ones. I have set clearOutsideBounds to false for now.
Please tell me if you would like me to change anything.
Happy to be contributing,
Kevin Luo

Added Indigenous Lands **Treaties** Layer. Indigenous Lands Treaties Inventory

---

Gruntfile.js
dist/LeafletEnvironmentalLayers.js
example/index.html
src/util/googleSpreadsheetLayer.js

Fixes #102 
I have implemented a method that will allow a google spreadsheet (that has been published and made available to anyone online) to be made into a layer.
Using this code:
We can do this:
This was a fun final task for GCI. Thank you for allowing me to have the chance to complete it :smile: . I will be happy to update the documentation after getting some sleep :zzz: .

Abstract Google Spreadsheet Method

---

dist/LeafletEnvironmentalLayers.js
example/index.html
package.json
src/leafletEnvironmentalLayers.js
src/osmLandfillMineQuarryLayer.js

Fixes #56 
I have added a layer for landfills, mines, and quarries through OSM:
Currently the colors are:
Red for Landfills,
Blue for Mines,
Green for Quarries
As I stated [here](https://github.com/publiclab/leaflet-environmental-layers/issues/56#issuecomment-443552850), I decided to parse the XML instead as the JSON output didn't provided the longitude latitude coordinates.
Currently the map is very slow, as you can see from the gif. It is possible I may have been above the quota. I am not too sure.
I have set the minimum zoom to 7 and clearOutsideBounds to false for now.
Please let me know if you would like me to change anything.
Also, thank you @sagarpreet-chadha . The spinner is super helpful when testing.
Thank you,
Kevin Luo

Osm landfill mine quarry

---

README.md
dist/LeafletEnvironmentalLayers.js
dist/legendCreation.js
example/index.html
src/util/getActiveOverlayNames.js
src/util/legendControl.js

Fixes #103 .
I have implemented a general control for the layers along with other functionality. Now any legend may be added with the syntax `addLayerNameURLPair( layer_var, img_url )`. The `layer_var` must be conistent with the one used in `index.html`.
I have placed my `src` files in a new folder called `util` since they were not really layers.
Example of working:

Adding legends 

---

dist/LeafletEnvironmentalLayers.js
src/osmLandfillMineQuarryLayer.js

The popup in osmLandfillMineQuarryLayer earlier displayed links as simple text. Changes have been made to display links using anchor tags.
fixes #42

display links in anchor tag in popup of osmLandfillMineQuarryLayer

---

dist/LeafletEnvironmentalLayers.js
example/index.html
src/leafletEnvironmentalLayers.js
src/luftdatenLayer.js

A new layer has been added that gets data from the luftdaten.info api in json format.
A get request is made to the [luftdaten.info API](https://maps.luftdaten.info/data/v2/data.dust.min.json)
fixes #88

add luftdaten.info air quality layer

---

dist/LeafletEnvironmentalLayers.js
example/index.html
src/leafletEnvironmentalLayers.js
src/openSenseLayer.js

A new layer has been added that gets data from opensensemap.org.
fixes #58

add opensensemap layer

---

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml
.github/first-timers-issue-template.md
.github/first-timers.yml

Fixes #159 
-Added PR and issue templates following the directory structure of plots2 repo.
-Updated the msg of the bot for newcomers according to plots2.

Added PR and issue templates according to plots2

---

example/index.html

Fixes #161 
Changed the names of baselayers as follows
- Baselayer1 -> Standard
- Baselayer2 -> Grey-scale
- Baselayer3 -> Streets
- Baselayer4 -> Dark

Changed the names of baselayers

---

spec/javascripts/fixtures/indigenousLanguagesLayers.html
spec/javascripts/fixtures/indigenousTerritoriesLayers.html
spec/javascripts/fixtures/indigenousTreatiesLayers.html
spec/javascripts/indigenousLanguagesLayers_spec.js
spec/javascripts/indigenousTerritoriesLayers_spec.js
spec/javascripts/indigenousTreatiesLayers_spec.js

[WIP] Test indigeneous layers

---

dist/LeafletEnvironmentalLayers.js
example/oneLinerCodeExample.html
package.json
src/AllLayers.js
src/info.json
src/layercode.js
src/osmLandfillMineQuarryLayer.js
src/toxicReleaseLayer.js
src/wisconsinLayer.js

Fixes  #110!
Fixes #208!
So only Wisconsin layer automatically zooms and pans the map on loading . 
So removed that feature .
Also minor bumped the version .
AND meta-data file created where we can give the information of each layer and when to call API (bounding box , min/max zoom , etc.) .

Removed all autopanning/zooming + Meta-data for layers API Call .

---

.eslintignore
.eslintrc.js
example/layers.js
package-lock.json
package.json
src/AllLayers.js
src/PLpeopleLayer.js
src/aqicnLayer.js
src/eonetFiresLayer.js
src/fracTrackerMobileLayer.js
src/indigenousLayers.js
src/layercode.js
src/leafletEnvironmentalLayers.js
src/legendCreation.js
src/openWeatherMapLayer.js
src/osmLandfillMineQuarryLayer.js
src/pfasLayer.js
src/purpleLayer.js
src/toxicReleaseLayer.js
src/unearthing.js
src/util/getActiveOverlayNames.js
src/util/googleSpreadsheetLayer.js
src/util/legendControl.js
src/util/spiderfyMarkers.js
src/windRoseLayer.js
src/wisconsinLayer.js

Fixes #301  (<=== Add issue number here)
Thanks!

Clean up code to have consistent formatting

---

.eslintrc.js
example/layers.js
example/oneLinerCodeExample.html
example/unearthing-pvd.html
src/AllLayers.js
src/util/embedControl.js

Fixes #306  (<=== Add issue number here)
Thanks!

Made domain name a settable domain name option

---

example/embed.html
example/layers.js
src/util/embedControl.js

Fixes #310  (<=== Add issue number here)
Thanks!

Clone demo page with embed pointing to the actual page

---

Gruntfile.js
_SpecRunner.html
spec/javascripts/embedControl.spec.js
spec/javascripts/fixtures/embedControl.html

Fixes #313  (<=== Add issue number here)
Thanks!

Add tests for embed feature

---

package.json
src/layerData.json

Fixes #316  (<=== Add issue number here)
Thanks!

Collect layer information

---

Gruntfile.js
_SpecRunner.html
example/layers.js
spec/javascripts/fracTrackerMobileLayer.spec.js
src/AllLayers.js
src/fracTrackerMobileLayer.js
src/layerData.json

Fixes #87  (<=== Add issue number here)
Thanks!

Implement changes to fractracker mobile layer

---

README.md
dist/LeafletEnvironmentalLayers.js
example/oneLinerCodeExample.html
package.json
src/AllLayers.js

Fixes #350  (<=== Add issue number here)
Thanks!

Add default basemap when undefined

---

dist/LeafletEnvironmentalLayers.js
example/layers.js
src/AllLayers.js
src/unearthing.js

Fixes #349 (<=== Add issue number here)
Thanks!

[WIP] Add layers in include to map by default

---

src/AllLayers.js

Fixed: Prevent use of the same default tile layer for multiple maps
Fixes #363  (<=== Add issue number here)
* [] screenshots/GIFs are attached 📎 in case of UI updation
Thanks!

Update AllLayers.js Fixed: Prevent use of the same default tile layer for multiple maps

---

dist/LeafletEnvironmentalLayers.js
example/oneLinerCodeExample.html
src/AllLayers.js

Fixes #377  (<=== Add issue number here)
There are cases in plots2 where we can't use a url hash to enable layers to be displayed. This param is optional and defaults to no layers being displayed on page load.
`include: ['layername']` will still limit what maps are available in the menu
`display: ['layername']` will turn on the specified layers, if they are available
`addLayersToMap: true` will override and display all layers that are available, regardless of what is in `display`

Add display parameter to show specific layers

---

_SpecRunner.html
dist/LeafletEnvironmentalLayers.js
example/multipleMaps.html
src/AllLayers.js

Fixes #395 (<=== Add issue number here)
This change should reset any subsequent maps to the correct default unless overriden by a new param.

Reformat init defaults

---

README.md
cypress/integration/eonetFiresLayer.spec.js
dist/LeafletEnvironmentalLayers.js
example/index.html
example/multipleMaps.html
example/oneLinerCodeExample.html
jsconfig.json
src/windRoseLayer.js

This is just some cleanup. I organized and labeled the required dependencies on each of the example map pages, as well as making them the same between the three of them and in the readme.
In the readme I've moved the "Browse layers" dependencies up to the main "Dependencies" section. I've also renamed it to "New Layers Menu" for clarity.

Example pages

---

CONTRIBUTING.md
README.md

Fixes #433  (<=== Add issue number here)
Thanks!

Update documentation on testing with Cypress

---

cypress/integration/layerFilter.spec.js

Fixes #423  (<=== Add issue number here)
Thanks!

Tests for layer filter feature

---

example/oneLinerCodeExample.html
example/unearthing-pvd.html
src/AllLayers.js

Fixes #369 (<=== Add issue number here)
Thanks!

Add search control to LEL's basic usage #369 Commit 

---

src/layercode.js

Fixes #384 
Replaced the skutruth-icons that were not showing with a circle marker.
Changes made only to layercode.js file.

Replacing the skytruth-icon with a circle marker

---

.github/workflows/tests.yml
cypress.json
cypress/integration/purpleAirMarker.spec.js
cypress/integration/skytruth.spec.js
src/layercode.js

Working from https://github.com/publiclab/leaflet-environmental-layers/blob/main/.travis.yml and https://github.com/publiclab/PublicLab.Editor/blob/main/.github/workflows/tests.yml

set up github actions CI instead of Travis

---

.gitpod.dockerfile
.gitpod.yml
README.md
cypress.json
package-lock.json
package.json

https://community.gitpod.io/t/rails-app-trying-to-get-chromedriver-working/1268
Fixes #0000 (<=== Add issue number here)
Thanks!

Allow cypress tests to be run in GitPod

---

src/openWeatherMapLayer.js

Supercedes #473 
We should be able to set this when we initialize LEL here using:
```js
options.imageLoadingUrl = "someGifAnimation.gif"
```
For example in plots2, here:
https://github.com/publiclab/plots2/blob/30fb69618430b589889f7e20cb8ce845e0b89e8d/app/assets/javascripts/leafletHelper.js#L116-L122

make owmloading.gif configurable option

---

cypress/integration/owm.spec.js
cypress/integration/purpleAirMarker.spec.js

Fix Cypress Tests

---

cypress/integration/aqicn.spec.js
package-lock.json
package.json

Fixed indigenous lands layers in one-liner constructor
Some progress on labeling AllLayers.js - https://github.com/publiclab/leaflet-environmental-layers/issues/665
Also - going to merge despite test failures, which have developed as APIs have changed, as has the data they return.

bump v2.4.9; indigenous lands layer fix for one-line constructor; commenting in AllLayers.js
